### ISSUE TITLE
How to use cargo

### ISSUE THREAD

**Issue by stukii** [PistonDevelopers/VisualRust#269]
Hello,

sorry to ask but I did not get it managed so far..
I want to use extensions/cargo in my code, how to to this?

After creating a Rust project through visual rust all I have is the "src" folder and the "main.rs" ... no cargo.toml.
Are there any detailed steps how to use... the rand lib for example?..

**Comment by Boddlnagg** [comment]
Unfortunately no version of VisualRust with Cargo integration has been released yet, because it lacks a bit of polish. You can uninstall VisualRust and try a recent build from our Continuous Integration instead: https://ci.appveyor.com/project/vosen/visualrust/build/145/artifacts

When you create a new Rust project with that version, it will have a `Cargo.toml` and you can add dependencies by editing that as usual.

**Comment by stukii** [comment]
Thank you! ♥♥♥
