### ISSUE TITLE
Show docs on F1

### ISSUE THREAD

**Issue by xilec** [PistonDevelopers/VisualRust#95]
To my mind, We need add VisualRust where we already can add some simple but useful commands. For instance:
* open official [Rust docs](http://doc.rust-lang.org/std/index.html) site with search by word on cursor position
* add/remove selected lines comments
and so on

**Comment by vosen** [comment]
No need for adding menu. Both those commands can be handled with existing VS infrastucture.
Check [this method[(http://blogs.msdn.com/b/dr._ex/archive/2007/04/17/using-enablevsiplogging-to-identify-menus-and-commands-with-vs-2005-sp1.aspx) to identify their guids and handle them.

Official docs can be opened by pressing F1 (C# uses this, try pressing F1 when you caret is inside a keyword). We should do the same.

**Comment by xilec** [comment]
I don't understand. What you mean in
> No need for adding menu. Both those commands can be handled with existing VS infrastucture.

Visual Studio supports different kinds of projects in a solution. For convenient user work in solution with many languages projects we shouldn't override default user's settings. In my opinion, we should add new commands which just should works in context of rust editor. In this case I don't understand where we can place this command except a own rust main menu?

**Comment by retep998** [comment]
There is already infrastructure in place so that when you press the key combination to comment or uncomment a section (`ctrl + k ctrl + c` and `ctrl + k ctrl + u`), it fires the appropriate language specific methods to comment/uncomment your block of code, as well as when you press the help button (`F1`), it fires a appropriate method to get help on whatever the mouse has selected.
All we'd have to do is hook into those and provide functionality specifically for when the user is working with Rust. We wouldn't be overriding the user's default settings.

**Comment by vosen** [comment]
Closed by #131
